sudo: false
language: python
matrix:
  include:
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.6'
      env: TOXENV=codestyle
    - python: '3.6'
      env: TOXENV=flakes
    - python: '3.6'
      env: TOXENV=pypi

# Run CI
install:
  - pip install tox
script:
  - tox
