sudo: false

language: python

matrix:
  include:
    - python: '3.6'
      env: TOXENV=nosetests
    - python: '3.7-dev'
      env: TOXENV=nosetests
    - python: '3.6'
      env: TOXENV=flake8
    - python: '3.6'
      env: TOXENV=doc8
    - python: '3.6'
      env: TOXENV=pypi

install:
  - pip install tox

script:
  - tox
