[tool.poetry]
name = "sphinx-revealjs"
version = "0.9.0"
description = "Sphinx extension with theme to generate Reveal.js presentation"
authors = ["Kazuya Takei <myself@attakei.net>"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Sphinx",
    "Framework :: Sphinx :: Extension",
    "ramework :: Sphinx :: Theme",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Topic :: Documentation :: Sphinx",
    "Topic :: Multimedia :: Graphics :: Presentation"
]
homepage = "https://github.com/attakei/sphinx-revealjs"
repository = "https://github.com/attakei/sphinx-revealjs"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.6 | ^3.7 | ^3.8"
docutils = "*"
sphinx = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
