name: Deploy demo presentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Make demo page
        run: |
          pip install -r demo/revealjs4/requirements.txt
          make -C demo/revealjs4 demo
          touch demo/revealjs4/_build/revealjs/.nojekyll
        env:
          GTAGJS_IDS: ${{ secrets.GTAGJS_IDS }}
      - name: Deploy to GitHub Pages
        uses: ftnext/action-push-ghpages@v1.0.0
        with:
          build_dir: demo/revealjs4/_build/revealjs/
          github_token: ${{ secrets.GITHUB_TOKEN }}
