name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Make demo page
        run: |
          python -m pip install --upgrade pip
          pip install .
          make -C demo revealjs
          touch demo/_build/revealjs/.nojekyll
      - name: Deploy to GitHub Pages
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: demo/_build/revealjs/
          GH_PAT: ${{ secrets.GH_PAT }}
