name: Check for update reveal.js

on:
  schedule:
    # TODO: Too short schedule
    - cron: '0,30 * * * *'

jobs:
  update-revealjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Try update package.json
        id: checked
        run: |
          version=`jq < package-lock.json '.dependencies."reveal.js".version' -r`
          echo "::set-output name=revealjs_current::${version}"
          npm i
          npm update
          version=`jq < package-lock.json '.dependencies."reveal.js".version' -r`
          echo "::set-output name=revealjs_updated::${version}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_PAT }}
          branch: update/revealjs-${{ steps.checked.outputs.revealjs_updated }}
          commit-message: "Update reveal.js"
          title: "Update reveal.js from v${{ steps.checked.outputs.revealjs_current }} to ${{ steps.checked.outputs.revealjs_updated }}"
          delete-branch: true
          body: |
            Please see [changelog of reveal.js](https://github.com/hakimel/reveal.js/releases/tag/${{ steps.checked.outputs.revealjs_updated}})

            Auto-generated by GitHub Actions
